# Generated by Django 4.2.19 on 2025-03-24 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CouncilMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="理事会名称")),
                ("content", models.TextField(verbose_name="内容")),
                ("location", models.CharField(max_length=200, verbose_name="地点")),
                ("meeting_time", models.DateTimeField(verbose_name="召开时间")),
                (
                    "invitation_sent",
                    models.BooleanField(default=False, verbose_name="是否已发送邀请"),
                ),
                (
                    "invitees",
                    models.ManyToManyField(
                        related_name="invited_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人员",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="召开人",
                    ),
                ),
            ],
            options={
                "verbose_name": "理事会",
                "verbose_name_plural": "理事会",
                "ordering": ["-meeting_time"],
            },
        ),
    ]
