# Generated by Django 4.2.19 on 2025-02-28 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("news", "新闻通知"),
                            ("activity", "活动通知"),
                            ("greeting", "节日祝福"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "send_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "receivers",
                    models.ManyToManyField(
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收人",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送人",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "notifications",
            },
        ),
    ]
