# Generated by Django 4.2.19 on 2025-03-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="status",
            field=models.IntegerField(
                choices=[(0, "发送成功"), (1, "发送失败")],
                default=0,
                verbose_name="发送状态",
            ),
        ),
    ]
