# Generated by Django 4.2.19 on 2025-03-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="created_at",
        ),
    ]
