# Generated by Django 4.2.19 on 2025-03-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="活动名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="活动介绍"),
                ),
                (
                    "applicant_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="申请人姓名"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="举办组织"
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="场地设施"
                    ),
                ),
                (
                    "apply_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="申请时间"
                    ),
                ),
                (
                    "event_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="活动举办时间"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "默认"),
                            (1, "申请中"),
                            (2, "已通过"),
                            (3, "已拒绝"),
                        ],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "校友活动",
                "verbose_name_plural": "校友活动",
                "db_table": "activities",
                "ordering": ["-apply_time"],
            },
        ),
        migrations.CreateModel(
            name="ActivityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "默认"),
                            (1, "申请中"),
                            (2, "已通过"),
                            (3, "已拒绝"),
                        ],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="activities.activity",
                        verbose_name="活动",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "活动成员",
                "verbose_name_plural": "活动成员",
                "db_table": "activity_members",
                "unique_together": {("activity", "user")},
            },
        ),
    ]
