# Generated by Django 4.2.19 on 2025-02-28 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "type",
                    models.CharField(
                        choices=[("general", "总会"), ("branch", "分会")],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                ("founding_date", models.DateField(verbose_name="成立日期")),
                (
                    "leader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_associations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="会长",
                    ),
                ),
            ],
            options={
                "verbose_name": "校友会",
                "verbose_name_plural": "校友会",
                "db_table": "associations",
            },
        ),
        migrations.CreateModel(
            name="AssociationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "会长"),
                            ("vice_president", "副会长"),
                            ("secretary", "秘书长"),
                            ("member", "会员"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "join_date",
                    models.DateField(auto_now_add=True, verbose_name="加入日期"),
                ),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="association.association",
                        verbose_name="校友会",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "校友会成员",
                "verbose_name_plural": "校友会成员",
                "db_table": "association_members",
            },
        ),
        migrations.AddField(
            model_name="association",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_associations",
                through="association.AssociationMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="成员",
            ),
        ),
        migrations.AddField(
            model_name="association",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="association.association",
                verbose_name="上级校友会",
            ),
        ),
    ]
