# Generated by Django 4.2.19 on 2025-03-02 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("association", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="association",
            name="parent",
        ),
        migrations.AddField(
            model_name="associationmember",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否在任"),
        ),
        migrations.AlterField(
            model_name="association",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="association",
            name="type",
            field=models.CharField(
                choices=[
                    ("general", "总会"),
                    ("college", "学院校友会"),
                    ("local", "地方校友会"),
                    ("overseas", "海外校友会"),
                    ("industry", "行业校友会"),
                ],
                max_length=20,
                verbose_name="类型",
            ),
        ),
        migrations.AlterField(
            model_name="associationmember",
            name="role",
            field=models.CharField(
                choices=[("president", "会长"), ("member", "会员")],
                default="member",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="associationmember",
            unique_together={("association", "user")},
        ),
        migrations.AddConstraint(
            model_name="association",
            constraint=models.UniqueConstraint(
                condition=models.Q(("type", "general")),
                fields=("type",),
                name="unique_general_association",
            ),
        ),
    ]
