# Generated by Django 4.2.19 on 2025-03-02 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("association", "0002_remove_association_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="associationmember",
            name="is_active",
        ),
    ]
