# Generated by Django 5.0.1 on 2025-03-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("association", "0003_remove_associationmember_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="association",
            name="mainImage",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="association_images/",
                verbose_name="主图",
            ),
        ),
        migrations.AddField(
            model_name="association",
            name="secondaryImage",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="association_images/",
                verbose_name="次图",
            ),
        ),
        migrations.AddField(
            model_name="associationmember",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否在任"),
        ),
    ]
