# Generated by Django 5.0.1 on 2025-03-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "association",
            "0004_association_mainimage_association_secondaryimage_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="association",
            name="mainImage",
        ),
        migrations.RemoveField(
            model_name="association",
            name="secondaryImage",
        ),
        migrations.RemoveField(
            model_name="associationmember",
            name="is_active",
        ),
        migrations.AddField(
            model_name="association",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="association_images/",
                verbose_name="图片",
            ),
        ),
    ]
