# Generated by Django 4.2.19 on 2025-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("association", "0005_remove_association_mainimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationmember",
            name="status",
            field=models.IntegerField(
                choices=[(0, "默认"), (1, "申请中"), (2, "已通过"), (3, "已拒绝")],
                default=0,
                verbose_name="状态",
            ),
        ),
    ]
