# Generated by Django 4.2.19 on 2025-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "校方管理员"),
                    ("liaison", "校友联络人"),
                    ("alumni", "未毕业校友"),
                    ("graduated_alumni", "毕业校友"),
                ],
                max_length=20,
                verbose_name="角色",
            ),
        ),
    ]
