# Generated by Django 4.2.19 on 2025-03-02 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="alumniprofile",
            name="is_graduated",
            field=models.IntegerField(
                choices=[(0, "未毕业"), (1, "已毕业"), (2, "审核中")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="alumniprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alumni_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
